name: test-action

on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    name: "Step 01"
    steps:
      - name: "Hello action"
        uses: gabriel-dantas98/find-pull-request-action@v1.3
        id: find-pr
        with:
          sha: ${{ github.event.sha }}
          repository: "gabriel-dantas98/klyntar"
